language: r
r:
  - devel
dist: bionic
cache: packages
warnings_are_errors: false
latex: false

# install debian libraries to match R-servers
# update pre-installed packages to latest versions
before_install:
  - export R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -qq update
  - sudo apt-get install -y libgdal-dev libproj-dev python-protobuf libprotoc-dev libprotobuf-dev libv8-dev librsvg2-dev libmpfr-dev libnlopt-dev libharfbuzz-dev libfribidi-dev
  - sudo add-apt-repository -y ppa:cran/libgit2
  - sudo apt-get -qq update
  - sudo apt-get install libgit2-dev
  - mkdir -p ~/.R/
  - echo "CXXFLAGS = `R CMD config CXXFLAGS` -g0 -flto -w" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -w -O3" >> ~/.R/Makevars
  - sudo apt-get install -y r-cran-rcppeigen
  - rcode="options('testthat.progress.max_fails' = Inf); "
  - rcode+="tfile <- tempfile(); capture.output(res<-devtools::test(), file = tfile); out <- readLines(tfile); cat(out, sep = '\n'); "
  - rcode+="line.fail <- max(grep('FAIL', out)); "
  - rcode+="tmp <- unlist(strsplit(split='[[:space:]]+', out[line.fail])); "
  - rcode+="pos.fail <- grep('FAIL', tmp); n.fail <- as.numeric(tmp[pos.fail+1]); "
  - rcode+="res <- as.data.frame(res); out <- data.frame(file = unlist(res[['file']]), warning = unlist(res[['warning']])); "
  - rcode+="write.csv(out, file='test_results.csv'); "
  - rcode+="quit(status = !identical(n.fail, 0), save='no');"
  - Rscript tools/travis_run_before_install.R

r_packages:
  - devtools
  - roxygen2
  - covr

r_github_packages:
  - Displayr/flipDevTools
  - Displayr/flipExampleData
  - CRAN/car@3.1-0

script:
  - R CMD build --no-manual --no-build-vignettes --no-resave-data .
  - R CMD check --as-cran --no-manual --no-build-vignettes --no-tests *.tar.gz
  - if [ -d tests/testthat ]; then
    Rscript --default-packages='datasets,utils,grDevices,graphics,stats,methods' -e "$rcode";
    fi

notifications:
  slack:
    rooms:
      secure: pROsuhN1u0+628SNI/iVtIChJgaxACXh0hSqXZ0am7rKoltSG8WEYaAx9J0tt3j1Whiu2hzE7q3pE3CCrW9paAl/HNrzSkSTGF3w4AZhEKarUfZjz3Pp6EF8wD+MaMcc8jTEtWVH+Ra0I06tRfr4BNQARFtOVzkfA0gkmRKgz1BSVYWHQaYAdbTuMnAP3RwyuKaeJeqITVhN/r8voe6F8PWwfuAdw7RY815dzKMEsBD5Ei7xXPx3n3lKDirLv/e+pv+f/g5VyvJSXg5W9XKLrcWifz6a5ntB2jWwqjZ94FVdEwIKfB8vwPlOoJ5RgufDH9bw86gbObLqVfKFyQSdLABAayLFUMgRtcvqatOS+Gb8wkL/RzUn/xHdfWHkknC1rXyKM5fHB6XzjNwpJGeSGCMfKptS5+2+TJagpneASnxYwhvS1xGVLf0crkbtLGodZLiYekmqUsz6EXjkDe0MXxPfbc1kr/FCx+eDUnh2iSFYPnoUYPDZJpN053yCp3/LKQbRcJcOqEZX+tHSLF6Ks8foEh4usCD1ml2Yv2byJnr+72C+UyWiZh4kdD4Fm6xqOtXF3Nxum+CyVIPVjs9VkRRiOZnSya6/QwZtpzhqlji4gr+6GMAzhxIxvoWg6i3FS9lqN8NQgXYDL4VhmvQCwlcnRydb16IN50bjlfK72nE=
    template:
      - "Build <%{build_url}|#%{build_number}> %{result} in %{repository_name}@%{branch} by %{author}: <%{compare_url}|%{commit_subject}>"
    on_success: change
    on_failure: always

# Warning notifications and downstream package builds are implemented
# by calling R functions so they can be updated in this package without
# committing a new change to .travis.yml in each repository
after_success:
  - Rscript -e "require(flipDevTools); NotifyWarnings(); TriggerDownstreamBuilds()"
  - travis_wait Rscript -e "flipDevTools::CheckCoverage()"
