name: Build flipAnalysisOfVariance

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build flipAnalysisOfVariance
    permissions:
      checks: write
      contents: read
    uses: Displayr/nixr-public/.github/workflows/build-flake-installable.yaml@master
    with:
      installable-path: pkgs.x86_64-linux.rPackages.flipAnalysisOfVariance
      build-args: --override-input flipAnalysisOfVariance .
      installable-name: flipAnalysisOfVariance
    secrets: inherit
